<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="LAPTOP-76KV8DF9" name="Selenium.MatchMakingTest" tests="2" failures="2" timestamp="11 Jun 2019 08:30:13 GMT" time="251.059" errors="0">
  <testcase name="matchMakingBetweenTwoPlayersPlayer1" time="117.092" classname="Selenium.MatchMakingTest">
    <failure type="java.lang.AssertionError" message="Failed due to an exception in getting element">
      <![CDATA[java.lang.AssertionError: Failed due to an exception in getting element
at org.junit.Assert.fail(Assert.java:88)
at Selenium.GenericWebDriver.getElementBy(GenericWebDriver.java:223)
at NirPages.SimulationPageNir.waitTillElementAboveSimulationIsLoaded(SimulationPageNir.java:96)
at Selenium.MatchMakingTest.matchMakingBetweenTwoPlayersPlayer1(MatchMakingTest.java:51)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- matchMakingBetweenTwoPlayersPlayer1 -->
  <testcase name="matchMakingBetweenTwoPlayersPlayer2" time="133.967" classname="Selenium.MatchMakingTest">
    <failure type="java.lang.AssertionError" message="Failed due to an exception in getting element">
      <![CDATA[java.lang.AssertionError: Failed due to an exception in getting element
at org.junit.Assert.fail(Assert.java:88)
at Selenium.GenericWebDriver.getElementBy(GenericWebDriver.java:223)
at NirPages.SimulationPageNir.waitTillElementAboveSimulationIsLoaded(SimulationPageNir.java:96)
at Selenium.MatchMakingTest.matchMakingBetweenTwoPlayersPlayer2(MatchMakingTest.java:106)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- matchMakingBetweenTwoPlayersPlayer2 -->
</testsuite> <!-- Selenium.MatchMakingTest -->
